name: Rails App Pipeline with Docker-Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make ENV File
      run: |
        touch .env
        echo "DB_USER=${{ secrets.APP_ENV_USER }}
        DB_PASSWORD=${{ secrets.APP_ENV_PASS }}
        REDIS_URL=${{ secrets.APP_ENV_REDISURL }}
        REDIS_PASSWORD=${{ secrets.APP_ENV_REDISPASS }}
        DO_REGISTRY_URL=${{ secrets.APP_ENV_DO_REG_PASS }}" >> .env
        pwd
        ls
        ls ~/
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        password: ${{ secrets.DO_PASSWORD }}
        port: 22
        source: "docker-compose.yml"
        target: "~/"
    - name: Build and Up Container
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up
        
    - name: Check Docker-Compose status
      run: |
        echo "DOCKER IMAGES"
        docker images
        echo "DOCKER PS -A"
        docker ps -a
        echo "DOCKER-COMPOSE IMAGES"
        docker-compose images
        echo "DOCKER_COMPOSE PS"
        docker-compose ps
    
    
    
    
    
    
    
    
